# https://taskfile.dev

version: "3"

includes:
  cpp:
    taskfile: ./cpp/Taskfile.yml
    dir: ./cpp
  julia:
    taskfile: ./julia/Taskfile.yml
    dir: ./julia
  rust:
    taskfile: ./rust/Taskfile.yml
    dir: ./rust
  numba:
    taskfile: ./numba/Taskfile.yml
    dir: ./numba
