[package]
name = "ising_rust"
version = "0.1.0"
authors = ["Zach Raines <raineszm@gmail.com>"]
edition = "2021"

[dependencies]
rand = { version = "^0.8", features = ["small_rng", "std"] }
num_cpus = "*"
